SELECT medal_id,
    case when medal_id = 1 then '爵位1'
         when medal_id = 2 then '爵位2'
         when medal_id = 3 then '爵位3'
         when medal_id = 4 then '爵位4'
         when medal_id = 5 then '爵位5'
         when medal_id = 6 then '爵位6'
         when medal_id = 7 then '总战力1'
         when medal_id = 8 then '总战力2'
         when medal_id = 9 then '总战力3'
         when medal_id = 10 then '秘境1'
         when medal_id = 11 then '秘境2'
         when medal_id = 12 then '秘境3'
         when medal_id = 13 then '积分赛1'
         when medal_id = 14 then '积分赛2'
         when medal_id = 15 then '积分赛3'
         when medal_id = 16 then '卡牌图鉴1'
         when medal_id = 17 then '卡牌图鉴2'
         when medal_id = 18 then '卡牌图鉴3'
         when medal_id = 19 then '登陆1'
         when medal_id = 20 then '登陆2'
         when medal_id = 21 then '登陆3'
         when medal_id = 22 then '友情点1'
         when medal_id = 23 then '友情点2'
         when medal_id = 24 then '友情点3'
         when medal_id = 25 then '世界boss1'
         when medal_id = 26 then '世界boss2'
         when medal_id = 27 then '世界boss3'
         when medal_id = 28 then '公会boss1'
         when medal_id = 29 then '公会boss2'
         when medal_id = 30 then '公会boss3'
         when medal_id = 31 then '装备副本1'
         when medal_id = 32 then '装备副本2'
         when medal_id = 33 then '装备副本3'
         when medal_id = 34 then '商店1'
         when medal_id = 35 then '商店2'
         when medal_id = 36 then '商店3'
         when medal_id = 37 then '神系秘境1'
         when medal_id = 38 then '神系秘境2'
         when medal_id = 39 then '神系秘境3'
         when medal_id = 40 then '神系秘境1'
         when medal_id = 41 then '神系秘境2'
         when medal_id = 42 then '神系秘境3'
         when medal_id = 43 then '神系秘境1'
         when medal_id = 44 then '神系秘境2'
         when medal_id = 45 then '神系秘境3'
         when medal_id = 46 then '神系秘境1'
         when medal_id = 47 then '神系秘境2'
         when medal_id = 48 then '神系秘境3'
         when medal_id = 49 then '神系秘境1'
         when medal_id = 50 then '神系秘境2'
         when medal_id = 51 then '神系秘境3'
         when medal_id = 52 then '神系秘境1'
         when medal_id = 53 then '神系秘境2'
         when medal_id = 54 then '神系秘境3'
    end as '勋章类型',
    count(distinct role_id) as '勋章激活人数'
from myth_server.server_medal_activation 
where day_time between ${beginDate} and ${endDate} and server_id in (${serverIds})
group by 1,2
order by 1